<?php

/**
 * Server-side language configuration for puzzle generation.
 * `generate_intro` and `lw_intro` use sprintf %d for the word count.
 * Ported from the original Node LANG_CONFIG.
 */

return [
    'de' => [
        'name' => 'Deutsch', 'dir' => 'ltr',
        'across_label' => 'Waagerecht →', 'down_label' => 'Senkrecht ↓',
        'solution_word_label' => 'Lösungswort',
        'char_rule' => "- \"word\": 4–9 Buchstaben, nur A–Z; Umlaute als AE, OE, UE; SS statt ß\n- \"clue\": ein kurzer, freundlicher Satz auf Deutsch\n- Bevorzuge Buchstaben E, N, R, S, T, A, I, O für gutes Vernetzen",
        'lw_char_rule' => '5–8 Buchstaben, deutsch, nur A–Z (Umlaute als AE, OE, UE, SS statt ß)',
        'lw_char_rule_after' => '4–9 Buchstaben, nur A–Z; Umlaute als AE, OE, UE; SS statt ß',
        'generate_intro' => 'Erstelle genau %d deutsche Wörter mit jeweils einem kurzen Hinweis (Rätselfrage) für ein Kreuzworträtsel.',
        'lw_intro' => 'Für ein Kreuzworträtsel mit etwa %d Begriffen wird **zuerst** das **Lösungswort** (Heft-Stil) und ein **Hinweis** festgelegt.',
        'scatter_hint' => 'Die kleinen Ziffern in den türkisen Marken unten rechts in den Kästchen (1, 2, 3 …) geben die Reihenfolge. Lesen Sie die Buchstaben nacheinander — so ergibt sich das Lösungswort.',
        'universal_hint' => 'Die türkisen Zahlmarken unten rechts in den weißen Kästchen (1, 2, 3 …) gehören zum Lösungswort — nicht die schwarzen Rätselnummern oben links. Tragen Sie die Buchstaben in die Kästchen unter dem Gitter ein. Je mehr Begriffe Sie lösen, desto mehr Buchstaben kennen Sie schon.',
        'mode_note' => 'Schwedenstil: Knappe Hinweise nur in der Liste unten. Im Gitter wie gewohnt nur Nummern.',
        'system_lang' => 'deutschsprachige',
    ],
    'es' => [
        'name' => 'Español', 'dir' => 'ltr',
        'across_label' => 'Horizontal →', 'down_label' => 'Vertical ↓',
        'solution_word_label' => 'Palabra Clave',
        'char_rule' => "- \"word\": 4–9 letras, solo A–Z sin tildes (normaliza á→A, é→E, ñ→N, etc.)\n- \"clue\": una frase breve y amable en español\n- Prefiere letras frecuentes: A, E, I, O, S, N, R, L",
        'lw_char_rule' => '5–8 letras, palabra española, solo A–Z sin tildes',
        'lw_char_rule_after' => '4–9 letras, solo A–Z sin tildes ni diacríticos',
        'generate_intro' => 'Crea exactamente %d palabras en español, cada una con una pista corta para un crucigrama. TODAS las palabras y pistas DEBEN estar en español.',
        'lw_intro' => 'Para un crucigrama de unos %d palabras, determina primero la PALABRA CLAVE y una pista. TODA la respuesta debe estar en español.',
        'scatter_hint' => 'Los pequeños números en las casillas indican el orden. Lee las letras en ese orden para encontrar la palabra clave.',
        'universal_hint' => 'Los números en turquesa en las casillas (1, 2, 3 …) pertenecen a la palabra clave. Escribe esas letras en las casillas de abajo. Cuantas más palabras resuelvas, más letras conocerás.',
        'mode_note' => 'Estilo sueco: Pistas breves solo en la lista inferior. Solo números en el tablero.',
        'system_lang' => 'en español',
    ],
    'it' => [
        'name' => 'Italiano', 'dir' => 'ltr',
        'across_label' => 'Orizzontale →', 'down_label' => 'Verticale ↓',
        'solution_word_label' => 'Parola Chiave',
        'char_rule' => "- \"word\": 4–9 lettere, solo A–Z senza accenti (normalizza à→A, è→E, ecc.)\n- \"clue\": una breve frase in italiano\n- Preferisci lettere frequenti: A, E, I, O, N, R, S, L",
        'lw_char_rule' => '5–8 lettere, parola italiana, solo A–Z senza accenti',
        'lw_char_rule_after' => '4–9 lettere, solo A–Z senza accenti',
        'generate_intro' => 'Crea esattamente %d parole in italiano, ognuna con un breve indizio per un cruciverba. TUTTE le parole e gli indizi DEVONO essere in italiano.',
        'lw_intro' => 'Per un cruciverba di circa %d parole, determina prima la PAROLA CHIAVE e un indizio. TUTTA la risposta deve essere in italiano.',
        'scatter_hint' => "I piccoli numeri nelle caselle indicano l'ordine. Leggi le lettere in quell'ordine per trovare la parola chiave.",
        'universal_hint' => 'I numeri in turchese nelle caselle (1, 2, 3 …) appartengono alla parola chiave. Scrivi quelle lettere nelle caselle in basso. Più parole risolvi, più lettere conoscerai.',
        'mode_note' => "Stile svedese: Suggerimenti brevi solo nell'elenco in basso. Solo numeri nel tabellone.",
        'system_lang' => 'in italiano',
    ],
    'tr' => [
        'name' => 'Türkçe', 'dir' => 'ltr',
        'across_label' => 'Yatay →', 'down_label' => 'Dikey ↓',
        'solution_word_label' => 'Çözüm Kelimesi',
        'char_rule' => "- \"word\": 4–9 harf, büyük Türkçe harfler (Ç, Ğ, İ, Ö, Ş, Ü dahil)\n- \"clue\": kısa, nazik bir Türkçe cümle\n- Sık kullanılan harfleri tercih et: A, E, İ, K, L, N, R, S",
        'lw_char_rule' => '5–8 harf, Türkçe kelime, büyük harfler (Ç, Ğ, İ, Ö, Ş, Ü dahil)',
        'lw_char_rule_after' => '4–9 harf, büyük Türkçe harfler',
        'generate_intro' => 'Tam olarak %d Türkçe kelime oluştur, her biri bir bulmaca için kısa bir ipucu ile. TÜM kelimeler ve ipuçları Türkçe OLMALIDIR.',
        'lw_intro' => 'Yaklaşık %d kelimeli bir bulmaca için önce ÇÖZÜM KELİMESİ ve bir ipucu belirle. Tüm yanıt Türkçe olmalı.',
        'scatter_hint' => 'Kutucuklardaki küçük rakamlar sırayı gösterir. Harfleri o sırayla okuyarak çözüm kelimesini bulun.',
        'universal_hint' => 'Kutucuklardaki turkuaz rakamlar (1, 2, 3 …) çözüm kelimesine aittir. O harfleri aşağıdaki kutucuklara yazın. Ne kadar çok kelime çözerseniz o kadar çok harf bilirsiniz.',
        'mode_note' => 'İsveç stili: Kısa ipuçları yalnızca aşağıdaki listede. Tabloda yalnızca numaralar.',
        'system_lang' => 'Türkçe',
    ],
    'ru' => [
        'name' => 'Русский', 'dir' => 'ltr',
        'across_label' => 'По горизонтали →', 'down_label' => 'По вертикали ↓',
        'solution_word_label' => 'Ключевое слово',
        'char_rule' => "- \"word\": 4–9 букв, только кириллица ЗАГЛАВНЫМИ (А–Я, Ё)\n- \"clue\": короткое дружелюбное предложение на русском языке\n- Предпочитай частые буквы: А, Е, И, Н, О, Р, С, Т",
        'lw_char_rule' => '5–8 букв, русское слово, только кириллица заглавными (А–Я, Ё)',
        'lw_char_rule_after' => '4–9 букв, только кириллица заглавными буквами',
        'generate_intro' => 'Создай ровно %d русских слов, каждое с коротким подсказом для кроссворда. ВСЕ слова и подсказы ДОЛЖНЫ быть на русском языке (кириллица).',
        'lw_intro' => 'Для кроссворда примерно из %d слов сначала определи КЛЮЧЕВОЕ СЛОВО и подсказ. Весь ответ должен быть на русском языке.',
        'scatter_hint' => 'Маленькие цифры в клетках указывают порядок. Читайте буквы в этом порядке, чтобы найти ключевое слово.',
        'universal_hint' => 'Бирюзовые цифры в клетках (1, 2, 3 …) относятся к ключевому слову. Впишите эти буквы в клетки ниже. Чем больше слов вы разгадаете, тем больше букв узнаете.',
        'mode_note' => 'Шведский стиль: Краткие подсказки только в списке ниже. В сетке только цифры.',
        'system_lang' => 'на русском языке',
    ],
    'el' => [
        'name' => 'Ελληνικά', 'dir' => 'ltr',
        'across_label' => 'Οριζόντια →', 'down_label' => 'Κάθετα ↓',
        'solution_word_label' => 'Λέξη-Κλειδί',
        'char_rule' => "- \"word\": 4–9 γράμματα, μόνο ελληνικά ΚΕΦΑΛΑΙΑ χωρίς τόνους\n- \"clue\": μια σύντομη φιλική πρόταση στα ελληνικά\n- Προτίμησε συχνά γράμματα: Α, Ε, Η, Ι, Κ, Ν, Ο, Σ, Τ",
        'lw_char_rule' => '5–8 γράμματα, ελληνική λέξη, κεφαλαία χωρίς τόνους',
        'lw_char_rule_after' => '4–9 γράμματα, μόνο ελληνικά κεφαλαία χωρίς τόνους',
        'generate_intro' => 'Δημιούργησε ακριβώς %d ελληνικές λέξεις, η καθεμία με μια σύντομη υπόδειξη για σταυρόλεξο. ΟΛΕΣ οι λέξεις και οι υποδείξεις ΠΡΕΠΕΙ να είναι στα ελληνικά.',
        'lw_intro' => 'Για ένα σταυρόλεξο με περίπου %d λέξεις, καθόρισε πρώτα τη ΛΕΞΗ-ΚΛΕΙΔΙ και μια υπόδειξη. Η απάντηση πρέπει να είναι στα ελληνικά.',
        'scatter_hint' => 'Τα μικρά νούμερα στα κελιά δείχνουν τη σειρά. Διαβάστε τα γράμματα με αυτή τη σειρά για να βρείτε τη λέξη-κλειδί.',
        'universal_hint' => 'Τα τιρκουάζ νούμερα στα κελιά (1, 2, 3 …) ανήκουν στη λέξη-κλειδί. Γράψτε τα γράμματα στα κελιά παρακάτω. Όσο περισσότερες λέξεις λύνετε, τόσο περισσότερα γράμματα γνωρίζετε.',
        'mode_note' => 'Σουηδικό στυλ: Σύντομες ενδείξεις μόνο στη λίστα παρακάτω. Στο πλέγμα μόνο αριθμοί.',
        'system_lang' => 'στα ελληνικά',
    ],
    'ar' => [
        'name' => 'العربية', 'dir' => 'rtl',
        'across_label' => '← أفقي', 'down_label' => '↓ عمودي',
        'solution_word_label' => 'كلمة الحل',
        'char_rule' => "- \"word\": 4–9 حروف، حروف عربية فقط بدون تشكيل (حركات)، اكتبها باللغة العربية\n- \"clue\": جملة قصيرة وودية باللغة العربية\n- فضل الحروف الشائعة: ا، ل، م، ن، و، ي، ه، ع",
        'lw_char_rule' => '5–8 حروف، كلمة عربية بدون تشكيل',
        'lw_char_rule_after' => '4–9 حروف، حروف عربية فقط بدون تشكيل',
        'generate_intro' => 'أنشئ بالضبط %d كلمة عربية، كل منها مع تلميح قصير لكلمة متقاطعة. يجب أن تكون جميع الكلمات والتلميحات باللغة العربية بدون تشكيل.',
        'lw_intro' => 'لكلمة متقاطعة من حوالي %d كلمة، حدد أولاً كلمة الحل وتلميحاً لها. يجب أن تكون جميع الإجابات باللغة العربية.',
        'scatter_hint' => 'الأرقام الصغيرة في الخلايا تشير إلى الترتيب. اقرأ الحروف بهذا الترتيب للحصول على كلمة الحل.',
        'universal_hint' => 'الأرقام الفيروزية في الخلايا (١، ٢، ٣ …) تنتمي إلى كلمة الحل. اكتب تلك الحروف في الخلايا أدناه.',
        'mode_note' => 'الأسلوب السويدي: تلميحات مختصرة في القائمة أدناه فقط. في الشبكة أرقام فقط.',
        'system_lang' => 'باللغة العربية',
    ],
];
